# Generated by Django 3.2.2 on 2021-05-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('answers', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=300)),
            ],
        ),
    ]
